version: "3.9"

services:
  db:
    container_name: "app_database"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tryon
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Asia/Bangkok"
    ports:
      - "5432:5432"
    volumes:
      - app_database:/var/lib/postgresql/data
    networks:
      - goservice
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tryon"]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  goservice:
    driver: bridge
  webproxy:
    external:
      name: webproxy
  default:
    external:
      name: kong_network

volumes:
  app_database:
